name: CI

on:
  push:
    branches: [ main ]
    tags:    [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build & Package
    runs-on: ubuntu-latest
    env:
      APP_NAME: sshconfiggui
      VERSION: "${{ github.ref_name }}"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            python3-tk gnupg2 pass \
            dpkg-dev fakeroot \
            squashfs-tools build-essential

          # Instalar snapcraft (desde Snap oficial)
          sudo snap install snapcraft --classic

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Download AppImageTool
        run: |
          wget -q https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage

      - name: Build all packages
        run: make all

      - name: Upload .deb artifact
        uses: actions/upload-artifact@master
        with:
          name: ${{ env.APP_NAME }}.deb
          path: build/${{ env.APP_NAME }}-${{ env.VERSION }}.deb

      - name: Upload AppImage artifact
        uses: actions/upload-artifact@master
        with:
          name: ${{ env.APP_NAME }}-AppImage
          path: "*.AppImage"

      - name: Upload Snap artifact
        uses: actions/upload-artifact@master
        with:
          name: ${{ env.APP_NAME }}.snap
          path: "*.snap"

  lint:
    name: Lint Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install flake8 and lint
        run: |
          python -m pip install flake8
          flake8 .
