name: CI

on:
  push:
    branches: [ main ]
    tags:    [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build & Package
    runs-on: ubuntu-latest
    env:
      APP_NAME: sshconfiggui
      VERSION: "1.0.0"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            python3-tk gnupg2 pass \
            dpkg-dev fakeroot \
            squashfs-tools build-essential

          # Instalar snapcraft desde Snap
          sudo snap install snapcraft --classic

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Download AppImageTool
        run: |
          wget -q https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O appimagetool
          chmod +x appimagetool

      - name: Ensure icon exists
        run: |
          mkdir -p resources
          if [ ! -f resources/sshconfiggui.png ]; then
            wget -O resources/sshconfiggui.png https://github.com/rpiera/sshConfigGUI/raw/main/resources/sshconfiggui.png || echo "No se pudo descargar ícono."
          fi

      - name: Build .deb and Snap packages
        run: make build-bin build-deb build-snap

      - name: Upload .deb artifact
        uses: actions/upload-artifact@master
        with:
          name: sshconfiggui.deb
          path: build/sshconfiggui-1.0.0.deb

      - name: Upload Snap artifact
        uses: actions/upload-artifact@master
        with:
          name: sshconfiggui.snap
          path: "*.snap"
