name: Artifact Test

on:
  push:
    branches: [ main ]

jobs:
  upload-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload README as dummy artifact
        uses: actions/upload-artifact@v3
        with:
          name: dummy-readme
          path: README.md
